export const ROOT_DIR = '.obsidian/plugins/zhinengchuangzuo/user_data'
export const TEMPLATE_DIR = 'templates'
export const CHAT_DIR = 'chats'
export const CONTEXT_DIR = 'contexts'
export const INITIAL_MIGRATION_MARKER = '.initial_migration_completed'
